name: helenundemil
description: Hochzeit Helen und Emil

version: 1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  bloc: ^7.0.0
  flutter_bloc: ^7.1.0
  logger: ^1.0.0
  flutter_svg: ^0.22.0
  http: ^0.13.3
  equatable: ^2.0.3
  json_annotation: ^4.0.1
  flutter_translate: ^3.0.1
  beamer: ^0.14.1
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  share_plus: ^2.1.4
  qr_flutter: ^4.0.0
  barcode_scan2: ^4.1.4
  url_launcher: ^6.0.9
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  json_serializable: any
  build_runner: ^2.1.0
  freezed: any
  pedantic: ^1.11.1
  mocktail: ^0.1.4
  fake_async: ^1.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  assets:
    - assets/i18n/
    - assets/images/
  fonts:
    - family: CrimsonPro
      fonts:
        - asset: fonts/CrimsonPro-VariableFont_wght.ttf
        - asset: fonts/CrimsonPro-Italic-VariableFont_wght.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
